config/routes.rb
PyCorporation::Application.routes.draw do
  get 'about' => 'pages#about'
  get 'faq' => 'pages#faq'
  root :to => 'pages#home'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def action
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_footer.html.erb
	<div class="footer">

	<small>
		Py Corporation by Maxime Orefice
	</small>
</div>

app/views/layouts/_header.html.erb
  <nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "PY CORPORATION", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <!--<ul class="nav navbar-nav">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>-->
      <ul class="nav navbar-nav navbar-right">
        <!--<li><a href="#">Link</a></li>-->
        <!-- class = active <\% if current_page?(action: 'process') %>-->
        <li><%= link_to "Acceuil", root_path %></li>
        <li><%= link_to "Contact", about_path %></li>
        <li><%= link_to "A Propos", faq_path %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Gallerie <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PyCorporation</title>
  <!-- Add Oxygen font from Google, doesn't work-->
  <%= stylesheet_link_tag    "application", "http://fonts.googleapis.com/css?family=Oxygen",
  media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track", "home" => true %>
  <%= csrf_meta_tags %>

<!-- TEST for the app on mobile -->
<meta name="viewport" content="width=device-width, initial-scale=1">

</head>
<body>

<%= render 'layouts/header' %>
<div class="container">
	<%= yield %>
	<%= render 'layouts/footer' %>
</div>
</body>
</html>

app/views/pages/about.html.erb
	<h1>Contact</h1>
<p> <strong>steven@gmail.com</strong>
</p>

<P>Actuellement étudiant en 3ème année dans une école d'ingénieur en Informatique (Epita), je vous propose des services personnalisés concernant le choix, le montage, l'installation et l'optimisation de votre futur ordinateur de bureau à votre domicile.

Inutile de préciser que les ordinateurs proposés sont bel et bien moins cher que ce que vous pouvez trouver dans le commerce. Le tout en fonction de votre budget et avec un service sur-mesure !

Cet ordinateur sera bien évidemment choisi en fonction de votre budget et sera parfaitement adapté à votre utilisation (bureautique, serveur, gamer, etc...).

Le matériel informatique brut (boitier, alimentation, carte mère, carte graphique GPU, processeur CPU, moniteur, etc...) sera acheté neuf en boutique et sera ensuite monté/installé par mes soins pour vous offrir un service 100% sur-mesure.
Ce service est bien évidemment garantie 6 mois contre tout vice matériel concernant cette main d'oeuvre. La garantie des pièces informatiques s'élève à 2 ans minimum selon le constructeur et est en aucun cas altérée.

N'hésitez plus si vous avez besoin d'un ordinateur adapté à vos besoins pour cette rentrée avec un prix et un service unique en Ile de France.

Les devis, renseignements, questions et conseils sont les bienvenus.

Avec plus d'une vingtaine d'ordinateurs montés durant les deux derniers mois (principalement gamer/haut de gamme), je vous propose un service de qualité et de confiance avant tout.

Service rapide : recevez votre nouveau PC en 48/72H

Trouvez dès à présent l'ordinateur qui vous convient sans vous ruiner.

Exemple de pc : i5 3570k 4670k i7 4770k GTX 780 770 Titan Corsair H110 H100i </P>

app/views/pages/faq.html.erb
<h1>A Propos</h1>
<p>
		Actuellement étudiant en 3ème année dans une école d'ingénieur en Informatique (Epita), je vous propose des services personnalisés concernant le choix, le montage, l'installation et l'optimisation de votre futur ordinateur de bureau à votre domicile.
</p>

app/views/pages/home.html.erb
<div class="container">
<div class="jumbotron">
<div class="row">
  <div class="col-md-6">
    <h1>Bienvenue sur PY CORPORATION</h1>
    <p>
      Montage pc gamer/haut de gamme sur mesure
    </p>
    <p><!-- Button trigger modal -->
<button class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">
  Demandez un devis dès à présent !
</button>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Devis</h4>
      </div>
      <div class="modal-body">
<div class="list-group">
<ul class="list-group">
  <li class="list-group-item">
    <form role="form">
      <div class="form-group">
        <input type="email" class="form-control" id="exampleInputEmail1" placeholder="Entrez votre email">
      </div>
    </form>
  </li>
    <li class="list-group-item">
    <form role="form">
      <div class="form-group">
        <input type="email" class="form-control" id="exampleInputEmail1" placeholder="Entrez votre nom">
      </div>
    </form>
  </li>
    <li class="list-group-item">
    <form role="form">
      <div class="form-group">
        <input type="email" class="form-control" id="exampleInputEmail1" placeholder="Entrez votre prénom">
      </div>
    </form>
  </li>
  <li class="list-group-item">Votre budget :<input type="range" />
  </li>
  <li class="list-group-item">Votre utilisation :
    <button type="button" class="btn btn-default">
    <span class="glyphicon glyphicon-play-circle"></span> Multimédia
    </button>
        <button type="button" class="btn btn-default">
    <span class="glyphicon glyphicon-off"></span> Jeux // Gaming
    </button>
        <button type="button" class="btn btn-default">
    <span class="glyphicon glyphicon-home"></span> Bureautique
    </button>
  </li>
</ul>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary">Envoyez</button>
      </div>
    </div>
  </div>
</div></p>
    <!--<p class="btn btn-default btn-lg" > <%= link_to "Sign Up Now!", "#" %> </p>-->
  </div>
</div>
<div class="col-md-6">
  <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner">
    <div class="item active">
      <%= image_tag("4.jpg") %>
      <div class="carousel-caption">
        
      </div>
    </div>
    <div class="item">
      <%= image_tag("5.jpg") %>
      <div class="carousel-caption">
        Une vingtaine d'ordinateurs montés durant les deux derniers mois (principalement gamer/haut de gamme).
      </div>
    </div>
    <div class="item">
      <%= image_tag("6.jpg") %>
      <div class="carousel-caption">
        Choix, montage, installation et l'optimisation de votre futur ordinateur de bureau à votre domicile.
      </div>
    </div>
  </div>

  <!-- Controls -->
  <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left"></span>
  </a>
  <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right"></span>
  </a>
</div>
</div>
</div>
<div class="row">
  <div class="col-md-6">
      <div>N'hésitez plus si vous avez besoin d'un ordinateur adapté à vos besoins pour cette rentrée avec un prix et un service unique en Ile de France.</div>
  </div>
</div>
</div>